# Generated by Django 3.2.8 on 2022-07-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начальная дата'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конечная дата'),
        ),
    ]
