# Generated by Django 3.2.8 on 2022-07-17 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_auto_20220711_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 17, 19, 23, 41, 781864), null=True, verbose_name='Прибытие'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 17, 19, 23, 41, 781864), null=True, verbose_name='Выезд'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='nights',
            field=models.PositiveIntegerField(default=0, verbose_name='ночи'),
        ),
    ]
