# Generated by Django 3.2.10 on 2022-07-24 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_auto_20220717_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 24, 18, 29, 0, 44533), null=True, verbose_name='Прибытие'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 24, 18, 29, 0, 44555), null=True, verbose_name='Выезд'),
        ),
    ]
