# Generated by Django 3.2.8 on 2022-07-17 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='date_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 17, 19, 23, 41, 781864), null=True, verbose_name='Прибытие'),
        ),
        migrations.AddField(
            model_name='basket',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 17, 19, 23, 41, 781864), null=True, verbose_name='Выезд'),
        ),
    ]
