# Generated by Django 3.2.10 on 2022-07-24 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20220717_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='date_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 24, 18, 29, 0, 41730), null=True, verbose_name='Прибытие'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 24, 18, 29, 0, 41750), null=True, verbose_name='Выезд'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='nights',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='кол-во ночей'),
        ),
    ]
