# Generated by Django 3.2.8 on 2022-07-08 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0002_alter_traveluser_first_name'),
        ('mainapp', '0002_accommodation_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость статьи')),
                ('accommodation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.accommodation')),
                ('travel_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel_user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.traveluserprofile')),
            ],
        ),
    ]
